### ISSUE TITLE
Misspell Light to Ligth

### ISSUE THREAD

**Issue by threeid** [0x9ef/vscode-vlang#1]
<img width="601" alt="Screen Shot 2019-06-20 at 10 21 59 AM" src="https://user-images.githubusercontent.com/37827220/59816216-7f57d580-9345-11e9-94e4-5b82eaf423a1.png">

Hi 0x9ef, 

Thank for the extension!

**Comment by 0x9ef** [comment]
Hi, thanks, currenty light theme unavaliable, use `V Development Dark` theme for better & beautiful syntax highlighting.
