### ISSUE TITLE
Function attributes have no scope

### ISSUE THREAD

**Issue by alexesprit** [0x9ef/vscode-vlang#106]
Was broken in c8dc0226b485ee7b5740d5de2117a6f408c42510.

![image](https://user-images.githubusercontent.com/1119267/72217978-6ebbb680-3546-11ea-9a2b-79a102d9de17.png)

**Comment by 0x9ef** [comment]
Fixed in https://github.com/0x9ef/vscode-vlang/commit/3e8f67f2abcb8e9ad8903b523ba8fd0ad16b4f67
