### ISSUE TITLE
#include SOMETHING breaks code highlighting

### ISSUE THREAD

**Issue by alexesprit** [0x9ef/vscode-vlang#115]
Example of file contains such inlclude:
https://github.com/vlang/v/blob/09d1eb7c558915c2d373a17344a65b21df559d9a/vlib/freetype/freetype.v#L36

Almost everything after this include is not highlighted. The file is valid, and can be compiled.

**Comment by 0x9ef** [comment]
Fixed in https://github.com/0x9ef/vscode-vlang/commit/b290d2d074d2150079a4dbb78367412d5a38bdba
