### ISSUE TITLE
multiline strings is not supported

### ISSUE THREAD

**Issue by aguspiza** [0x9ef/vscode-vlang#12]

**Comment by 0x9ef** [comment]
Can you provide more info? For me multiline strings supported.

**Comment by aguspiza** [comment]
https://github.com/vlang/v/blob/master/vlib/builtin/string_test.v#L114

This line starts a multiline and I get this highlighted as code:
```
fn main() {
        println(2)
}
```

**Comment by 0x9ef** [comment]
Fixed ([#d09fcfd](https://github.com/0x9ef/vscode-vlang/blob/master/syntaxes/v.tmLanguage.json)).
