### ISSUE TITLE
Numbers in exponential form highlighted incorrectly

### ISSUE THREAD

**Issue by alexesprit** [0x9ef/vscode-vlang#127]
```v
fn main() {
	a := 1e-6
	b := 1e+6
}
```

| V  | C (how it should be)  | 
|---|---|
| ![image](https://user-images.githubusercontent.com/1119267/74106706-f31b4c80-4b79-11ea-8e8f-028116397464.png)  | ![image](https://user-images.githubusercontent.com/1119267/74106711-fca4b480-4b79-11ea-91dd-9a87ca14c060.png)  |

**Comment by 0x9ef** [comment]
Fixed in https://github.com/0x9ef/vscode-vlang/commit/6b58431cd51cb4449924aece54998d5b0751c4a1
