### ISSUE TITLE
.v file icon

### ISSUE THREAD

**Issue by proneon267** [0x9ef/vscode-vlang#15]
![Screenshot from 2019-07-13 20-11-48](https://user-images.githubusercontent.com/45512885/61173002-98515080-a5aa-11e9-9548-5033bcf92d91.png)
here main.v file should also have a icon of v like the makefile has a icon of its own.

**Comment by 0x9ef** [comment]
I know, i have a .ico file for V, but i dont know ho to install it.

**Comment by proneon267** [comment]
Check https://code.visualstudio.com/api/extension-guides/icon-theme
https://code.visualstudio.com/api/extension-capabilities/theming#adding-a-new-icon-theme

**Comment by proneon267** [comment]
I looked at https://github.com/0x9ef/vscode-vlang/blob/master/theme/icon-theme.json
you should also add languageIds
```
"languageIds": {
    "v": "_v_file"
  }
```

**Comment by proneon267** [comment]
Probably you should remove 
```
"fileNames": {
        ".v": "_v_file"
    }
```
and add `languageIds` as from https://code.visualstudio.com/api/extension-guides/icon-theme:
>fileNames associates file names to icons. The key in the set is the full file name, not including any path segments. Patterns or wildcards are not supported. File name matching is case insensitive. A 'fileName' match is the strongest match, and the icon associated to the file name will be preferred over an icon of a matching fileExtension and also of a matching language Id.

that means it will only show the icon if the filename is `.v` and not when the file extension is `.v`

**Comment by 0x9ef** [comment]
Unsuccessfully :(

```json
{
    "iconDefinitions": {
        "_v_file": {
            "iconPath": "./icon16.png"
        }
    },
    "fileExtensions": {
        "v": "_v_file"
    },
    "languageIds": {
        "v": "_v_file"
    },
}
```

You can see changes at `icontheme` branch.
https://github.com/0x9ef/vscode-vlang/tree/icontheme

**Comment by Alhadis** [comment]
[This might help](https://github.com/0x9ef/vscode-vlang/pull/19/files?short_path=6404561#diff-6404561f5689667db110a8a3811e736f). I noticed [`theme/images/v.svg`](https://github.com/0x9ef/vscode-vlang/blob/b190c016b7b297c0ac78bc613b2e78a473d2b859/theme/images/v.svg) contained invalid SVG source (and the icon simply wasn't displaying when I downloaded it), so I fixed it.

In any case, I happened to add V to the [latest release of `file-icons`](https://marketplace.visualstudio.com/manage/publishers/file-icons) the other night, so I suspect icon-availability shouldn't be a hassle. 😀
