### ISSUE TITLE
Language Server Protocol

### ISSUE THREAD

**Issue by mrgaturus** [0x9ef/vscode-vlang#16]
if you will implement an IntelliSense, Code diagnostic and Code testing for V. You can implement those as a Language Server Protocol, it allows VSCode and other editors (Vim, Sublime Text, Atom, etc) use it easily.

**Comment by 0x9ef** [comment]
I can not implement LSP for V because i don't know TypeScript :(

**Comment by mrgaturus** [comment]
implementing a LSP doesn't need Typescript :), see the code from LSPs for other languages

**Comment by 0x9ef** [comment]
I know, but its takes a lot of time and skill to implement.
