### ISSUE TITLE
Use Go `.tmLanguage` code formatting

### ISSUE THREAD

**Issue by nedpals** [0x9ef/vscode-vlang#17]
Since V's grammar is syntactically synonymous to Go's, instead of creating a new one, why not fork Go's `.tmLanguage` grammar and just modify it little bit since creating a new one from scratch is a very complex task. Plus, devs can use the themes of their choice while coding programs in V.

**Comment by 0x9ef** [comment]
I already wrote a grammar for V from scratch. I will not use Go grammar for current repo.
I will remove `dev-dark-color-theme` in few time.
