### ISSUE TITLE
Conflicting scopeName in testv.tmLanguage.json

### ISSUE THREAD

**Issue by Alhadis** [0x9ef/vscode-vlang#18]
Hey there,

[I'm arranging](https://github.com/github/linguist/pull/4564) to have this grammar used on GitHub.com to provide syntax highlighting for V, and I noticed there are two different grammars with conflicting `scopeName` fields:

* [`syntaxes/testv.tmLanguage.json`](https://github.com/0x9ef/vscode-vlang/blob/57e9ea6112d7dbcd55e7e645c1e1f692cf64839a/syntaxes/testv.tmLanguage.json#L7): `"source.v"`
* [`syntaxes/v.tmLanguage.json`](https://github.com/0x9ef/vscode-vlang/blob/57e9ea6112d7dbcd55e7e645c1e1f692cf64839a/syntaxes/v.tmLanguage.json#L8):  `"source.v"`

The `scopeName` field is like an identifier; it's supposed to be unique between grammars. I'm not sure what `testv.tmLanguage.json` is being used for, but it looks like `v.tmLanguage.json` is the correct grammar for highlighting V code.

I recommend either removing `testv.tmLanguage.json`, or changing its `scopeName` to be something like `source.v.test` or something similar to differentiate it from the "real" V grammar.

Thanks in advance!

**Comment by 0x9ef** [comment]
No problems :)

**Comment by medvednikov** [comment]
https://github.com/0x9ef/vscode-vlang/commit/4e3a35358d7927efbd47b25911b50e9ad3ee1cd2

Thanks @0x9ef

**Comment by Alhadis** [comment]
Wow. Thanks for getting that actioned so quickly! 😀
