### ISSUE TITLE
How to run my v code from VS Code ?

### ISSUE THREAD

**Issue by vinodvinu** [0x9ef/vscode-vlang#26]
Hi, 
I've installed this extension. Its working ok, now, how do i run my code ? Is there any keyboard short cuts ? Or do i need to type the command in terminal ? If so please guide me how to do it.

**Comment by 0x9ef** [comment]
You cannot run V from VSCode because this extension currently not supporting running single file or project by hotkey. You can run new terminal by CTRL+SHIFT+\` and compile V file by `v myfile.v`

**Comment by vinodvinu** [comment]
Somehow, i have partially succeeded in running v code from VS code with the extension "code-runner". So, now, i dont need to type my file name in terminal. (think about a lengthy file name) Code runner saved me.
