### ISSUE TITLE
`match` replaced `switch`

### ISSUE THREAD

**Issue by tomByrer** [0x9ef/vscode-vlang#31]
https://github.com/vlang/v/blob/master/CHANGELOG.md#v-0122

> switch has been completely removed from the language and replaced by match everywhere.

Not sure if you / VSCode / TM have a "deprecated" keyword or color set up yet?

**Comment by ahgm** [comment]
fixed :
https://github.com/ahgm/vscode-vlang

**Comment by ahgm** [comment]
thanks ! solved

**Comment by 0x9ef** [comment]
Changed since last commit! https://github.com/0x9ef/vscode-vlang/commit/3e8e19df20d65afcb87655f5aa9920b14bd765c2
