### ISSUE TITLE
highlight of `struct` and `interface`

### ISSUE THREAD

**Issue by ghost** [0x9ef/vscode-vlang#331]
left: Go
right: V

V's `sturct` is not colored like in Go.
Would nice to be colored
![範囲を選択_001](https://user-images.githubusercontent.com/52106048/138894994-8b2bd626-402d-4f5e-a1ad-c74fce06f0c2.png)
.

**Comment by danieldaeschle** [comment]
On my theme there is no color. I also can't find the difference. Is it still an issue?
