### ISSUE TITLE
Struct field type is not highlighted if default value is specified

### ISSUE THREAD

**Issue by alexesprit** [0x9ef/vscode-vlang#55]
V allows to specify default values of struct fields. But in this case the extension does not highlight field type (GitHub doesn't do too, lol):
```v
struct Test {
	field1 string
	field2 string = ''
}
```

![image](https://user-images.githubusercontent.com/1119267/71615874-800ad780-2bc4-11ea-8472-438796fcd15d.png)

**Comment by Alhadis** [comment]
> GitHub doesn't do too, lol

GitHub is using this package for highlighting V syntax, so it's no surprise, lol.
