### ISSUE TITLE
Enum name has no "entity.name.enum.v" scope when enum is public

### ISSUE THREAD

**Issue by dhonx** [0x9ef/vscode-vlang#62]
<img src="https://i.ibb.co/5GmC106/Screenshot-from-2020-01-01-02-33-21.png" alt="Screenshot-from-2020-01-01-02-33-21" width="150%">

**Comment by 0x9ef** [comment]
Will fixed in https://github.com/0x9ef/vscode-vlang/pull/61 after review.

**Comment by 0x9ef** [comment]
Fixed.
