### ISSUE TITLE
`fn` keyword has no scope if function modifier is used

### ISSUE THREAD

**Issue by alexesprit** [0x9ef/vscode-vlang#68]
`fn` keyword has no scope if function modifier is on the same line. V allows both variants.

![image](https://user-images.githubusercontent.com/1119267/71642365-3b159c80-2cbb-11ea-81fb-fc13ddcb29d0.png)

```v
[inline]
fn inlined_function1() bool {
	return true
}

[inline] fn inlined_function2() bool {
	return true
}
```

**Comment by alexesprit** [comment]
Also, the name of the `inlined_function2` function has a wrong scope (`support.function.v`, but should be `entity.name.function.v`).

**Comment by 0x9ef** [comment]
Will fixed in https://github.com/0x9ef/vscode-vlang/pull/61

**Comment by 0x9ef** [comment]
Fixed.
