### ISSUE TITLE
`onDidCloseTerminal` is applied multiple times

### ISSUE THREAD

**Issue by alexesprit** [0x9ef/vscode-vlang#70]
In the [src/client/run.ts][runts] an event listener is applied every time a user run a V file:
```ts
	vscode.window.onDidCloseTerminal(term => {
		if (term.name == 'V') { 
			vRunTerm = null; 
		} 
	});
```
The listener should be applied if nessessary (e.g. when assigning a value to `vRunTerm` variable).

[runts]: https://github.com/0x9ef/vscode-vlang/blob/b247c9fce1dbb660be7ca8bd4d37e9c42a19240a/src/client/run.ts#L13

**Comment by dhonx** [comment]
Yeah, agree, the listener should be registered once.
