### ISSUE TITLE
Reverse changelog

### ISSUE THREAD

**Issue by alexesprit** [0x9ef/vscode-vlang#71]
In the changelog is said that:

> The format is based on Keep a Changelog, and this project adheres to Semantic Versioning.

One of [principles][principles] of Keep a Changelog is to sort changelogs in a way where the latest version is on top of changelog. This is also quite convinient: most users want to read the latest changes, so they don't waste their time to scroll the whole changelog if the latest changes come first.

What are your thoughts on this?

If it should be reversed, I can do all dirty work and submit a PR.

[principles]: https://keepachangelog.com/en/1.0.0/#how

**Comment by dhonx** [comment]
Yeah... good find @alexesprit !!  👍

**Comment by Acid147** [comment]
Good idea. You might want to wait until my pull request (#59) is merged. I fixed a lot of Markdown issues in the changelog, so it might make sense to avoid merge conflicts.

**Comment by alexesprit** [comment]
@Acid147 sure, I'll wait.

**Comment by Acid147** [comment]
It's been merged, you can go ahead.
