### ISSUE TITLE
Show version info

### ISSUE THREAD

**Issue by Acid147** [0x9ef/vscode-vlang#74]
Is the command `v.ver` supposed to show the version of this extension or the version of V?

**Comment by 0x9ef** [comment]
Yeah.

**Comment by Acid147** [comment]
Which one is it? And is that functionality actually useful? I think both can easily be checked without this extension. If it is, I'll try to get it working.

**Comment by 0x9ef** [comment]
Oh, sorry, i forget to write for what supposed :) Supposed for version of V.
