### ISSUE TITLE
Error while packing extension by `vsce package`

### ISSUE THREAD

**Issue by 0x9ef** [0x9ef/vscode-vlang#94]
OS: `Windows 10`
Run: `vsce package`

When i try to pack extension into `.vsix` i getting next error:
`ERROR  SVGs are restricted in README.md; please use other file image formats, such as PNG: https://github.com/0x9ef/vscode-vlang/workflows/CI/badge.svg`. How to resolve this?

**Comment by dhonx** [comment]
Maybe this could work... 🙂
```md
![GitHub Workflow Status](https://img.shields.io/github/workflow/status/0x9ef/vscode-vlang/CI?style=for-the-badge)
```
![GitHub Workflow Status](https://img.shields.io/github/workflow/status/0x9ef/vscode-vlang/CI?style=for-the-badge)

**Comment by alexesprit** [comment]
The only way is to use allowed 3rd-party badge services, e.g. shields.io.
