### ISSUE TITLE
Numbers have no `constant.numeric.integer.v` scope in some cases

### ISSUE THREAD

**Issue by alexesprit** [0x9ef/vscode-vlang#98]
In this example `1` has different scopes in different contexts:
```v
fn test_and() {
	c:=[1,2,3,4,5]
	assert c[0] & 1 != 0 // constant.numeric.integer.v
	assert c[1] & 1 == 0 // variable.assignment.other.v
	assert c[2] & 1 != 0 // constant.numeric.integer.v
	assert c[3] & 1 == 0 // variable.assignment.other.v
	assert c[4] & 1 != 0 // constant.numeric.integer.v
}
```

That leads to invalid highlighting in cases, where `constant.numeric.integer.v` is missing:
![image](https://user-images.githubusercontent.com/1119267/72025474-4f443580-3289-11ea-8824-ee588a2cab82.png)

It should be `constant.numeric.integer.v` for `1` in every case.

**Comment by 0x9ef** [comment]
Fixed in https://github.com/0x9ef/vscode-vlang/commit/c8dc0226b485ee7b5740d5de2117a6f408c42510
